import celticsLogo from "../../assets/teams/celtics.png";
import patriotsLogo from "../../assets/teams/patriots.png";
import redSoxLogo from "../../assets/teams/redsox.png";
import type {
  FollowedSourcePreference,
  LeagueId,
  NewsItem,
  NewsSource,
  SportId,
} from "./types";

const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

export const sportOptions = [
  { id: "football", label: "Football" },
  { id: "baseball", label: "Baseball" },
  { id: "basketball", label: "Basketball" },
] as const satisfies readonly { id: SportId; label: string }[];

export const leagueOptions = [
  { id: "nfl", label: "NFL", sportId: "football" },
  { id: "cfl", label: "CFL", sportId: "football" },
  { id: "ufl", label: "UFL", sportId: "football" },
  { id: "mlb", label: "MLB", sportId: "baseball" },
  { id: "milb", label: "MiLB", sportId: "baseball" },
  { id: "nba", label: "NBA", sportId: "basketball" },
  { id: "wnba", label: "WNBA", sportId: "basketball" },
] as const satisfies readonly { id: LeagueId; label: string; sportId: SportId }[];

export const mockSourceCatalog = [
  {
    id: "fan-field-journal",
    name: "Fan Field Journal",
    initials: "FF",
    description: "Independent reporting and analysis from around the football world.",
    category: "Media Outlet",
    accessStatus: "usable",
    contentTypes: ["Article", "News", "League Update"],
    sportTags: ["football"],
  },
  {
    id: "gridiron-north",
    name: "Gridiron North",
    initials: "GN",
    description: "Canadian football stories, film notes, and game-day reporting.",
    category: "Blogger",
    accessStatus: "usable",
    contentTypes: ["Blog", "News"],
    sportTags: ["football"],
  },
  {
    id: "diamond-line",
    name: "The Diamond Line",
    initials: "DL",
    description: "Daily baseball reporting from the majors through the farm system.",
    category: "Media Outlet",
    accessStatus: "usable",
    contentTypes: ["Article", "News", "Team Update"],
    sportTags: ["baseball"],
  },
  {
    id: "hardwood-standard",
    name: "Hardwood Standard",
    initials: "HS",
    description: "Basketball reporting, roster analysis, and league-wide features.",
    category: "Media Outlet",
    accessStatus: "usable",
    contentTypes: ["Article", "News", "League Update"],
    sportTags: ["basketball"],
  },
  {
    id: "weekend-sports-radio",
    name: "Weekend Sports Radio",
    initials: "WS",
    description: "A mock podcast network covering pro football across North America.",
    category: "Podcast",
    accessStatus: "usable",
    contentTypes: ["Podcast"],
    sportTags: ["football"],
  },
  {
    id: "film-room-lab",
    name: "Film Room Lab",
    initials: "FR",
    description: "Creator-led tactical breakdowns and short-form analysis.",
    category: "Creator",
    accessStatus: "usable",
    contentTypes: ["Blog", "Video"],
    sportTags: ["football", "basketball"],
  },
  {
    id: "stadium-social",
    name: "Stadium Social",
    initials: "SS",
    description: "A mock social source with only partial catalog support.",
    category: "Creator",
    accessStatus: "partial",
    contentTypes: ["Video"],
    sportTags: ["football", "baseball", "basketball"],
  },
] as const satisfies readonly NewsSource[];

export function createInitialFollowedSourcePreferences(): FollowedSourcePreference[] {
  const initiallyFollowedIds = new Set([
    "fan-field-journal",
    "gridiron-north",
    "diamond-line",
    "hardwood-standard",
    "weekend-sports-radio",
  ]);

  return mockSourceCatalog
    .filter((source) => initiallyFollowedIds.has(source.id))
    .map((source) => ({
      sourceId: source.id,
      contentTypes: [...source.contentTypes],
      mutedUntil: null,
    }));
}

export const mockNewsItems = [
  {
    id: "patriots-camp-tempo",
    sourceId: "fan-field-journal",
    headline: "Patriots turn up the tempo as the offense enters its final camp phase",
    byline: "Maya Bennett",
    contentType: "Article",
    publishedAt: hoursAgo(0.5),
    summary: "New England used a faster practice script while testing combinations across the offensive line.",
    body: [
      "New England moved through its sharpest practice of the week with a noticeably quicker offensive tempo and several new line combinations.",
      "Coaches described the session as a useful stress test rather than a permanent change. The emphasis was on communication, clean substitutions, and making decisions before the defense could settle.",
      "The next practice is expected to shift back toward situational work, including late-game drives and red-zone packages.",
    ],
    sport: "football",
    league: "nfl",
    teamIds: ["new-england-patriots"],
    viewType: "local",
    imageUrl: patriotsLogo,
    imageAlt: "New England Patriots logo",
    viewCount: 3240,
    reactionCount: 241,
  },
  {
    id: "cfl-stretch-race",
    sourceId: "gridiron-north",
    headline: "Three adjustments reshaping the CFL playoff race",
    byline: "Noah Cardinal",
    contentType: "Blog",
    publishedAt: hoursAgo(1.2),
    summary: "Protection changes and more aggressive second-down decisions are shifting the league table.",
    body: [
      "The CFL playoff picture is beginning to move as clubs adjust protection calls and become more aggressive on second down.",
      "The most successful teams are creating easier throws without giving up the explosive plays that define the Canadian game.",
      "This mock analysis combines recent trends into one league-wide snapshot for FANatical's demonstration feed.",
    ],
    sport: "football",
    league: "cfl",
    teamIds: [],
    viewType: "local",
    viewCount: 1880,
    reactionCount: 118,
  },
  {
    id: "red-sox-bullpen-plan",
    sourceId: "diamond-line",
    headline: "Red Sox map out a flexible bullpen plan for the coming series",
    byline: "Elena Cruz",
    contentType: "Team Update",
    publishedAt: hoursAgo(1.8),
    summary: "Boston is preparing several late-inning combinations instead of assigning one fixed path.",
    body: [
      "Boston will enter the coming series with a flexible late-inning plan built around matchups and recent workload.",
      "The approach gives the club more options when the highest-leverage moment arrives before the ninth inning.",
      "Coaches said roles remain clear internally even if the order changes from night to night.",
    ],
    sport: "baseball",
    league: "mlb",
    teamIds: ["boston-red-sox"],
    viewType: "local",
    imageUrl: redSoxLogo,
    imageAlt: "Boston Red Sox logo",
    viewCount: 2910,
    reactionCount: 193,
  },
  {
    id: "ufl-schedule-podcast",
    sourceId: "weekend-sports-radio",
    headline: "Podcast: What the new UFL schedule could mean for spring football",
    byline: "Weekend Sports Radio Desk",
    contentType: "Podcast",
    publishedAt: hoursAgo(2.5),
    summary: "A roundtable looks at travel, rivalry windows, and how the schedule creates meaningful late-season games.",
    body: [],
    sport: "football",
    league: "ufl",
    teamIds: [],
    viewType: "external",
    externalDestination: "Weekend Sports Radio episode page",
    viewCount: 1490,
    reactionCount: 94,
  },
  {
    id: "celtics-rotation-options",
    sourceId: "hardwood-standard",
    headline: "Celtics test two rotation ideas designed for smaller, faster lineups",
    byline: "Jordan Lee",
    contentType: "Article",
    publishedAt: hoursAgo(3.1),
    summary: "Boston is exploring lineups that preserve spacing while keeping enough size on the glass.",
    body: [
      "Boston's latest rotation experiments are designed to preserve spacing without surrendering defensive rebounding.",
      "The first group leans into speed and early offense. The second keeps an additional ball-handler on the floor for more deliberate half-court possessions.",
      "Neither look is final, but both show how the coaching staff can adapt when matchups pull traditional bigs away from the basket.",
    ],
    sport: "basketball",
    league: "nba",
    teamIds: ["boston-celtics"],
    viewType: "local",
    imageUrl: celticsLogo,
    imageAlt: "Boston Celtics logo",
    viewCount: 4270,
    reactionCount: 356,
  },
  {
    id: "nfl-kickoff-rule",
    sourceId: "fan-field-journal",
    headline: "NFL clubs continue adapting roster decisions to the kickoff format",
    byline: "Andre Wallace",
    contentType: "League Update",
    publishedAt: hoursAgo(4.5),
    summary: "Special-teams versatility is affecting the final few roster spots across the league.",
    body: [],
    sport: "football",
    league: "nfl",
    teamIds: [],
    viewType: "external",
    externalDestination: "Fan Field Journal league desk",
    viewCount: 5210,
    reactionCount: 404,
  },
  {
    id: "milb-prospect-wave",
    sourceId: "diamond-line",
    headline: "The next wave of MiLB call-up candidates is taking shape",
    byline: "Samir Patel",
    contentType: "Article",
    publishedAt: hoursAgo(5),
    summary: "Five skill profiles that could help major-league clubs during the stretch run.",
    body: [
      "The next group of potential call-ups includes contact hitters, multi-position defenders, and relievers with swing-and-miss pitches.",
      "Production matters, but clubs are also weighing roster flexibility and whether each player has a clear path to regular playing time.",
      "FANatical's mock article demonstrates how a development-league item can appear in the broader Baseball feed.",
    ],
    sport: "baseball",
    league: "milb",
    teamIds: [],
    viewType: "local",
    viewCount: 970,
    reactionCount: 63,
  },
  {
    id: "wnba-expansion-depth",
    sourceId: "hardwood-standard",
    headline: "WNBA expansion is creating a new kind of roster-depth conversation",
    byline: "Avery Morgan",
    contentType: "News",
    publishedAt: hoursAgo(6.2),
    summary: "Front offices are balancing immediate depth against the long-term value of player development.",
    body: [
      "Expansion planning is placing new attention on the middle of WNBA rosters and the value of versatile depth.",
      "Teams must weigh current lineup needs against the risk of losing players who could grow into larger roles.",
      "The decisions will influence both the new clubs and the competitive balance of the existing league.",
    ],
    sport: "basketball",
    league: "wnba",
    teamIds: [],
    viewType: "local",
    viewCount: 2210,
    reactionCount: 176,
  },
  {
    id: "ufl-motion-film",
    sourceId: "film-room-lab",
    headline: "Film Room: The motion concept spreading across the UFL",
    byline: "Film Room Lab",
    contentType: "Video",
    publishedAt: hoursAgo(7),
    summary: "A creator breakdown of the pre-snap movement opening space against pressure looks.",
    body: [],
    sport: "football",
    league: "ufl",
    teamIds: [],
    viewType: "external",
    externalDestination: "Film Room Lab video page",
    viewCount: 3460,
    reactionCount: 289,
  },
  {
    id: "cfl-stadium-atmosphere",
    sourceId: "gridiron-north",
    headline: "Five rivalry games set to define the CFL's late-summer atmosphere",
    byline: "Noah Cardinal",
    contentType: "News",
    publishedAt: hoursAgo(8),
    summary: "A look ahead at the matchups most likely to reshape momentum in the standings and stands.",
    body: [
      "The late-summer calendar brings together five rivalry games with consequences for both the standings and supporter momentum.",
      "Each matchup features a different tension: recent playoff history, regional pride, or a race for position entering the final stretch.",
      "The result is a run of games built for the league-wide Football feed as well as future event and Cheer connections.",
    ],
    sport: "football",
    league: "cfl",
    teamIds: [],
    viewType: "local",
    viewCount: 1320,
    reactionCount: 101,
  },
  {
    id: "red-sox-farm-defense",
    sourceId: "diamond-line",
    headline: "Boston's farm system puts a new emphasis on defensive flexibility",
    byline: "Elena Cruz",
    contentType: "Blog",
    publishedAt: hoursAgo(9),
    summary: "Several Red Sox prospects are adding positions without losing their primary development focus.",
    body: [
      "Boston is asking several prospects to add defensive flexibility while keeping one position at the center of their development plans.",
      "The goal is not to turn every player into a utility option. It is to create more paths to major-league playing time when opportunities arise.",
      "That flexibility is already changing how affiliates construct late-game lineups.",
    ],
    sport: "baseball",
    league: "milb",
    teamIds: ["boston-red-sox"],
    viewType: "local",
    imageUrl: redSoxLogo,
    imageAlt: "Boston Red Sox logo",
    viewCount: 1640,
    reactionCount: 87,
  },
  {
    id: "patriots-audio-notebook",
    sourceId: "weekend-sports-radio",
    headline: "Audio notebook: Reading the Patriots defense before the snap",
    byline: "Weekend Sports Radio Desk",
    contentType: "Podcast",
    publishedAt: hoursAgo(11),
    summary: "A practice-field discussion about communication, disguise, and how the secondary passes off routes.",
    body: [],
    sport: "football",
    league: "nfl",
    teamIds: ["new-england-patriots"],
    viewType: "external",
    externalDestination: "Weekend Sports Radio episode page",
    viewCount: 2380,
    reactionCount: 152,
  },
  {
    id: "nba-bench-creation",
    sourceId: "hardwood-standard",
    headline: "Why secondary creation has become the NBA's most valuable bench skill",
    byline: "Jordan Lee",
    contentType: "Article",
    publishedAt: hoursAgo(12),
    summary: "Teams are prioritizing reserves who can keep an offense organized without dominating the ball.",
    body: [
      "NBA teams are placing a premium on reserves who can create an advantage without requiring every possession to run through them.",
      "The best examples combine quick decisions, reliable spacing, and enough defensive versatility to stay on the floor in different matchups.",
      "That skill set is changing both free-agent evaluation and the way second units are assembled.",
    ],
    sport: "basketball",
    league: "nba",
    teamIds: [],
    viewType: "local",
    viewCount: 6190,
    reactionCount: 488,
  },
] as const satisfies readonly NewsItem[];

export function findNewsSource(sourceId: string) {
  return mockSourceCatalog.find((source) => source.id === sourceId);
}
